// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.29.0
// source: ng_driver.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExtensionType int32

const (
	ExtensionType_STRING        ExtensionType = 0
	ExtensionType_INT           ExtensionType = 1
	ExtensionType_FLOAT         ExtensionType = 2
	ExtensionType_BOOL          ExtensionType = 3
	ExtensionType_STRING_ARRAY  ExtensionType = 4
	ExtensionType_INTEGER_ARRAY ExtensionType = 5
	ExtensionType_FLOAT_ARRAY   ExtensionType = 6
	ExtensionType_BOOLEAN_ARRAY ExtensionType = 7
	ExtensionType_ENUM          ExtensionType = 8
	ExtensionType_ENUM_ARRAY    ExtensionType = 9
)

// Enum value maps for ExtensionType.
var (
	ExtensionType_name = map[int32]string{
		0: "STRING",
		1: "INT",
		2: "FLOAT",
		3: "BOOL",
		4: "STRING_ARRAY",
		5: "INTEGER_ARRAY",
		6: "FLOAT_ARRAY",
		7: "BOOLEAN_ARRAY",
		8: "ENUM",
		9: "ENUM_ARRAY",
	}
	ExtensionType_value = map[string]int32{
		"STRING":        0,
		"INT":           1,
		"FLOAT":         2,
		"BOOL":          3,
		"STRING_ARRAY":  4,
		"INTEGER_ARRAY": 5,
		"FLOAT_ARRAY":   6,
		"BOOLEAN_ARRAY": 7,
		"ENUM":          8,
		"ENUM_ARRAY":    9,
	}
)

func (x ExtensionType) Enum() *ExtensionType {
	p := new(ExtensionType)
	*p = x
	return p
}

func (x ExtensionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExtensionType) Descriptor() protoreflect.EnumDescriptor {
	return file_ng_driver_proto_enumTypes[0].Descriptor()
}

func (ExtensionType) Type() protoreflect.EnumType {
	return &file_ng_driver_proto_enumTypes[0]
}

func (x ExtensionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExtensionType.Descriptor instead.
func (ExtensionType) EnumDescriptor() ([]byte, []int) {
	return file_ng_driver_proto_rawDescGZIP(), []int{0}
}

type Operator int32

const (
	Operator_EQ          Operator = 0
	Operator_NEQ         Operator = 1
	Operator_GT          Operator = 2
	Operator_GTE         Operator = 3
	Operator_LT          Operator = 4
	Operator_LTE         Operator = 5
	Operator_CONTAINS    Operator = 6
	Operator_PREFIX      Operator = 7
	Operator_SUFFIX      Operator = 8
	Operator_REGEX       Operator = 9
	Operator_IN          Operator = 10
	Operator_NOT_IN      Operator = 11
	Operator_BETWEEN     Operator = 12
	Operator_NOT_BETWEEN Operator = 13
	Operator_NOT_NULL    Operator = 14
)

// Enum value maps for Operator.
var (
	Operator_name = map[int32]string{
		0:  "EQ",
		1:  "NEQ",
		2:  "GT",
		3:  "GTE",
		4:  "LT",
		5:  "LTE",
		6:  "CONTAINS",
		7:  "PREFIX",
		8:  "SUFFIX",
		9:  "REGEX",
		10: "IN",
		11: "NOT_IN",
		12: "BETWEEN",
		13: "NOT_BETWEEN",
		14: "NOT_NULL",
	}
	Operator_value = map[string]int32{
		"EQ":          0,
		"NEQ":         1,
		"GT":          2,
		"GTE":         3,
		"LT":          4,
		"LTE":         5,
		"CONTAINS":    6,
		"PREFIX":      7,
		"SUFFIX":      8,
		"REGEX":       9,
		"IN":          10,
		"NOT_IN":      11,
		"BETWEEN":     12,
		"NOT_BETWEEN": 13,
		"NOT_NULL":    14,
	}
)

func (x Operator) Enum() *Operator {
	p := new(Operator)
	*p = x
	return p
}

func (x Operator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operator) Descriptor() protoreflect.EnumDescriptor {
	return file_ng_driver_proto_enumTypes[1].Descriptor()
}

func (Operator) Type() protoreflect.EnumType {
	return &file_ng_driver_proto_enumTypes[1]
}

func (x Operator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operator.Descriptor instead.
func (Operator) EnumDescriptor() ([]byte, []int) {
	return file_ng_driver_proto_rawDescGZIP(), []int{1}
}

type EnumValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Types that are assignable to Value:
	//
	//	*EnumValue_StringValue
	//	*EnumValue_IntValue
	//	*EnumValue_FloatValue
	//	*EnumValue_BoolValue
	Value isEnumValue_Value `protobuf_oneof:"value"`
}

func (x *EnumValue) Reset() {
	*x = EnumValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ng_driver_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnumValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumValue) ProtoMessage() {}

func (x *EnumValue) ProtoReflect() protoreflect.Message {
	mi := &file_ng_driver_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumValue.ProtoReflect.Descriptor instead.
func (*EnumValue) Descriptor() ([]byte, []int) {
	return file_ng_driver_proto_rawDescGZIP(), []int{0}
}

func (x *EnumValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (m *EnumValue) GetValue() isEnumValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *EnumValue) GetStringValue() string {
	if x, ok := x.GetValue().(*EnumValue_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (x *EnumValue) GetIntValue() int64 {
	if x, ok := x.GetValue().(*EnumValue_IntValue); ok {
		return x.IntValue
	}
	return 0
}

func (x *EnumValue) GetFloatValue() float32 {
	if x, ok := x.GetValue().(*EnumValue_FloatValue); ok {
		return x.FloatValue
	}
	return 0
}

func (x *EnumValue) GetBoolValue() bool {
	if x, ok := x.GetValue().(*EnumValue_BoolValue); ok {
		return x.BoolValue
	}
	return false
}

type isEnumValue_Value interface {
	isEnumValue_Value()
}

type EnumValue_StringValue struct {
	StringValue string `protobuf:"bytes,2,opt,name=stringValue,proto3,oneof"`
}

type EnumValue_IntValue struct {
	IntValue int64 `protobuf:"varint,3,opt,name=intValue,proto3,oneof"`
}

type EnumValue_FloatValue struct {
	FloatValue float32 `protobuf:"fixed32,4,opt,name=floatValue,proto3,oneof"`
}

type EnumValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,5,opt,name=boolValue,proto3,oneof"`
}

func (*EnumValue_StringValue) isEnumValue_Value() {}

func (*EnumValue_IntValue) isEnumValue_Value() {}

func (*EnumValue_FloatValue) isEnumValue_Value() {}

func (*EnumValue_BoolValue) isEnumValue_Value() {}

type EnumArrayType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []*EnumValue `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *EnumArrayType) Reset() {
	*x = EnumArrayType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ng_driver_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnumArrayType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumArrayType) ProtoMessage() {}

func (x *EnumArrayType) ProtoReflect() protoreflect.Message {
	mi := &file_ng_driver_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumArrayType.ProtoReflect.Descriptor instead.
func (*EnumArrayType) Descriptor() ([]byte, []int) {
	return file_ng_driver_proto_rawDescGZIP(), []int{1}
}

func (x *EnumArrayType) GetValues() []*EnumValue {
	if x != nil {
		return x.Values
	}
	return nil
}

type StringArray struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *StringArray) Reset() {
	*x = StringArray{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ng_driver_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringArray) ProtoMessage() {}

func (x *StringArray) ProtoReflect() protoreflect.Message {
	mi := &file_ng_driver_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringArray.ProtoReflect.Descriptor instead.
func (*StringArray) Descriptor() ([]byte, []int) {
	return file_ng_driver_proto_rawDescGZIP(), []int{2}
}

func (x *StringArray) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type IntArray struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []int64 `protobuf:"varint,1,rep,packed,name=values,proto3" json:"values,omitempty"`
}

func (x *IntArray) Reset() {
	*x = IntArray{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ng_driver_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IntArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntArray) ProtoMessage() {}

func (x *IntArray) ProtoReflect() protoreflect.Message {
	mi := &file_ng_driver_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntArray.ProtoReflect.Descriptor instead.
func (*IntArray) Descriptor() ([]byte, []int) {
	return file_ng_driver_proto_rawDescGZIP(), []int{3}
}

func (x *IntArray) GetValues() []int64 {
	if x != nil {
		return x.Values
	}
	return nil
}

type FloatArray struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []float32 `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"`
}

func (x *FloatArray) Reset() {
	*x = FloatArray{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ng_driver_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FloatArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloatArray) ProtoMessage() {}

func (x *FloatArray) ProtoReflect() protoreflect.Message {
	mi := &file_ng_driver_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloatArray.ProtoReflect.Descriptor instead.
func (*FloatArray) Descriptor() ([]byte, []int) {
	return file_ng_driver_proto_rawDescGZIP(), []int{4}
}

func (x *FloatArray) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type BooleanArray struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []bool `protobuf:"varint,1,rep,packed,name=values,proto3" json:"values,omitempty"`
}

func (x *BooleanArray) Reset() {
	*x = BooleanArray{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ng_driver_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BooleanArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BooleanArray) ProtoMessage() {}

func (x *BooleanArray) ProtoReflect() protoreflect.Message {
	mi := &file_ng_driver_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BooleanArray.ProtoReflect.Descriptor instead.
func (*BooleanArray) Descriptor() ([]byte, []int) {
	return file_ng_driver_proto_rawDescGZIP(), []int{5}
}

func (x *BooleanArray) GetValues() []bool {
	if x != nil {
		return x.Values
	}
	return nil
}

type Condition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Operator Operator `protobuf:"varint,1,opt,name=operator,proto3,enum=ng_proto.Operator" json:"operator,omitempty"`
	// Types that are assignable to Value:
	//
	//	*Condition_StringValue
	//	*Condition_IntValue
	//	*Condition_FloatValue
	//	*Condition_BoolValue
	//	*Condition_StringArray
	//	*Condition_IntArray
	//	*Condition_FloatArray
	//	*Condition_BoolArray
	Value isCondition_Value `protobuf_oneof:"value"`
}

func (x *Condition) Reset() {
	*x = Condition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ng_driver_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Condition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition) ProtoMessage() {}

func (x *Condition) ProtoReflect() protoreflect.Message {
	mi := &file_ng_driver_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition.ProtoReflect.Descriptor instead.
func (*Condition) Descriptor() ([]byte, []int) {
	return file_ng_driver_proto_rawDescGZIP(), []int{6}
}

func (x *Condition) GetOperator() Operator {
	if x != nil {
		return x.Operator
	}
	return Operator_EQ
}

func (m *Condition) GetValue() isCondition_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *Condition) GetStringValue() string {
	if x, ok := x.GetValue().(*Condition_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (x *Condition) GetIntValue() int64 {
	if x, ok := x.GetValue().(*Condition_IntValue); ok {
		return x.IntValue
	}
	return 0
}

func (x *Condition) GetFloatValue() float32 {
	if x, ok := x.GetValue().(*Condition_FloatValue); ok {
		return x.FloatValue
	}
	return 0
}

func (x *Condition) GetBoolValue() bool {
	if x, ok := x.GetValue().(*Condition_BoolValue); ok {
		return x.BoolValue
	}
	return false
}

func (x *Condition) GetStringArray() *StringArray {
	if x, ok := x.GetValue().(*Condition_StringArray); ok {
		return x.StringArray
	}
	return nil
}

func (x *Condition) GetIntArray() *IntArray {
	if x, ok := x.GetValue().(*Condition_IntArray); ok {
		return x.IntArray
	}
	return nil
}

func (x *Condition) GetFloatArray() *FloatArray {
	if x, ok := x.GetValue().(*Condition_FloatArray); ok {
		return x.FloatArray
	}
	return nil
}

func (x *Condition) GetBoolArray() *BooleanArray {
	if x, ok := x.GetValue().(*Condition_BoolArray); ok {
		return x.BoolArray
	}
	return nil
}

type isCondition_Value interface {
	isCondition_Value()
}

type Condition_StringValue struct {
	StringValue string `protobuf:"bytes,2,opt,name=stringValue,proto3,oneof"`
}

type Condition_IntValue struct {
	IntValue int64 `protobuf:"varint,3,opt,name=intValue,proto3,oneof"`
}

type Condition_FloatValue struct {
	FloatValue float32 `protobuf:"fixed32,4,opt,name=floatValue,proto3,oneof"`
}

type Condition_BoolValue struct {
	BoolValue bool `protobuf:"varint,5,opt,name=boolValue,proto3,oneof"`
}

type Condition_StringArray struct {
	StringArray *StringArray `protobuf:"bytes,6,opt,name=stringArray,proto3,oneof"`
}

type Condition_IntArray struct {
	IntArray *IntArray `protobuf:"bytes,7,opt,name=intArray,proto3,oneof"`
}

type Condition_FloatArray struct {
	FloatArray *FloatArray `protobuf:"bytes,8,opt,name=floatArray,proto3,oneof"`
}

type Condition_BoolArray struct {
	BoolArray *BooleanArray `protobuf:"bytes,9,opt,name=boolArray,proto3,oneof"`
}

func (*Condition_StringValue) isCondition_Value() {}

func (*Condition_IntValue) isCondition_Value() {}

func (*Condition_FloatValue) isCondition_Value() {}

func (*Condition_BoolValue) isCondition_Value() {}

func (*Condition_StringArray) isCondition_Value() {}

func (*Condition_IntArray) isCondition_Value() {}

func (*Condition_FloatArray) isCondition_Value() {}

func (*Condition_BoolArray) isCondition_Value() {}

type Extension struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field      string        `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Label      string        `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Type       ExtensionType `protobuf:"varint,3,opt,name=type,proto3,enum=ng_proto.ExtensionType" json:"type,omitempty"`
	EnumInfo   []*EnumValue  `protobuf:"bytes,4,rep,name=enumInfo,proto3" json:"enumInfo,omitempty"`
	Conditions []*Condition  `protobuf:"bytes,5,rep,name=conditions,proto3" json:"conditions,omitempty"`
	Required   bool          `protobuf:"varint,6,opt,name=required,proto3" json:"required,omitempty"`
}

func (x *Extension) Reset() {
	*x = Extension{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ng_driver_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Extension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Extension) ProtoMessage() {}

func (x *Extension) ProtoReflect() protoreflect.Message {
	mi := &file_ng_driver_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Extension.ProtoReflect.Descriptor instead.
func (*Extension) Descriptor() ([]byte, []int) {
	return file_ng_driver_proto_rawDescGZIP(), []int{7}
}

func (x *Extension) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *Extension) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Extension) GetType() ExtensionType {
	if x != nil {
		return x.Type
	}
	return ExtensionType_STRING
}

func (x *Extension) GetEnumInfo() []*EnumValue {
	if x != nil {
		return x.EnumInfo
	}
	return nil
}

func (x *Extension) GetConditions() []*Condition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *Extension) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

type DriverMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name                string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description         string       `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Version             string       `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Extensions          []*Extension `protobuf:"bytes,4,rep,name=extensions,proto3" json:"extensions,omitempty"`
	DataPointExtensions []*Extension `protobuf:"bytes,5,rep,name=dataPointExtensions,proto3" json:"dataPointExtensions,omitempty"`
	ActionExtensions    []*Extension `protobuf:"bytes,6,rep,name=actionExtensions,proto3" json:"actionExtensions,omitempty"`
	EventExtensions     []*Extension `protobuf:"bytes,7,rep,name=eventExtensions,proto3" json:"eventExtensions,omitempty"`
}

func (x *DriverMetadata) Reset() {
	*x = DriverMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ng_driver_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DriverMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverMetadata) ProtoMessage() {}

func (x *DriverMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_ng_driver_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverMetadata.ProtoReflect.Descriptor instead.
func (*DriverMetadata) Descriptor() ([]byte, []int) {
	return file_ng_driver_proto_rawDescGZIP(), []int{8}
}

func (x *DriverMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DriverMetadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DriverMetadata) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DriverMetadata) GetExtensions() []*Extension {
	if x != nil {
		return x.Extensions
	}
	return nil
}

func (x *DriverMetadata) GetDataPointExtensions() []*Extension {
	if x != nil {
		return x.DataPointExtensions
	}
	return nil
}

func (x *DriverMetadata) GetActionExtensions() []*Extension {
	if x != nil {
		return x.ActionExtensions
	}
	return nil
}

func (x *DriverMetadata) GetEventExtensions() []*Extension {
	if x != nil {
		return x.EventExtensions
	}
	return nil
}

var File_ng_driver_proto protoreflect.FileDescriptor

var file_ng_driver_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6e, 0x67, 0x5f, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x08, 0x6e, 0x67, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xaa, 0x01, 0x0a, 0x09,
	0x45, 0x6e, 0x75, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x22, 0x0a, 0x0b, 0x73,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x0b, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x1c, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x48, 0x00, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x20, 0x0a,
	0x0a, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x02, 0x48, 0x00, 0x52, 0x0a, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x1e, 0x0a, 0x09, 0x62, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x08, 0x48, 0x00, 0x52, 0x09, 0x62, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42,
	0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x3c, 0x0a, 0x0d, 0x45, 0x6e, 0x75, 0x6d,
	0x41, 0x72, 0x72, 0x61, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2b, 0x0a, 0x06, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6e, 0x67, 0x5f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x06,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x25, 0x0a, 0x0b, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x22, 0x0a,
	0x08, 0x49, 0x6e, 0x74, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x73, 0x22, 0x24, 0x0a, 0x0a, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12,
	0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x02, 0x52,
	0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x26, 0x0a, 0x0c, 0x42, 0x6f, 0x6f, 0x6c, 0x65,
	0x61, 0x6e, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x08, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22,
	0xa5, 0x03, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2e, 0x0a,
	0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x12, 0x2e, 0x6e, 0x67, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x52, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x22, 0x0a,
	0x0b, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x1c, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x20, 0x0a, 0x0a, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x02, 0x48, 0x00, 0x52, 0x0a, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x1e, 0x0a, 0x09, 0x62, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x09, 0x62, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x39, 0x0a, 0x0b, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x41, 0x72, 0x72, 0x61, 0x79,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6e, 0x67, 0x5f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x41, 0x72, 0x72, 0x61, 0x79, 0x48, 0x00, 0x52,
	0x0b, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x30, 0x0a, 0x08,
	0x69, 0x6e, 0x74, 0x41, 0x72, 0x72, 0x61, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x6e, 0x67, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x74, 0x41, 0x72, 0x72,
	0x61, 0x79, 0x48, 0x00, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x36,
	0x0a, 0x0a, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x41, 0x72, 0x72, 0x61, 0x79, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6e, 0x67, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x6c,
	0x6f, 0x61, 0x74, 0x41, 0x72, 0x72, 0x61, 0x79, 0x48, 0x00, 0x52, 0x0a, 0x66, 0x6c, 0x6f, 0x61,
	0x74, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x36, 0x0a, 0x09, 0x62, 0x6f, 0x6f, 0x6c, 0x41, 0x72,
	0x72, 0x61, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6e, 0x67, 0x5f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e, 0x41, 0x72, 0x72, 0x61,
	0x79, 0x48, 0x00, 0x52, 0x09, 0x62, 0x6f, 0x6f, 0x6c, 0x41, 0x72, 0x72, 0x61, 0x79, 0x42, 0x07,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xe6, 0x01, 0x0a, 0x09, 0x45, 0x78, 0x74, 0x65,
	0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c,
	0x61, 0x62, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65,
	0x6c, 0x12, 0x2b, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x17, 0x2e, 0x6e, 0x67, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x78, 0x74, 0x65, 0x6e,
	0x73, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x2f,
	0x0a, 0x08, 0x65, 0x6e, 0x75, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x6e, 0x67, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6e, 0x75, 0x6d,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x08, 0x65, 0x6e, 0x75, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x33, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x05, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6e, 0x67, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43,
	0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64,
	0x22, 0xdc, 0x02, 0x0a, 0x0e, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x33, 0x0a, 0x0a, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6e, 0x67, 0x5f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x65, 0x78,
	0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x45, 0x0a, 0x13, 0x64, 0x61, 0x74, 0x61,
	0x50, 0x6f, 0x69, 0x6e, 0x74, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6e, 0x67, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x13, 0x64, 0x61, 0x74, 0x61,
	0x50, 0x6f, 0x69, 0x6e, 0x74, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x3f, 0x0a, 0x10, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6e, 0x67, 0x5f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x10,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x12, 0x3d, 0x0a, 0x0f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6e, 0x67, 0x5f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0f,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2a,
	0x9c, 0x01, 0x0a, 0x0d, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x54, 0x52, 0x49, 0x4e, 0x47, 0x10, 0x00, 0x12, 0x07, 0x0a,
	0x03, 0x49, 0x4e, 0x54, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x46, 0x4c, 0x4f, 0x41, 0x54, 0x10,
	0x02, 0x12, 0x08, 0x0a, 0x04, 0x42, 0x4f, 0x4f, 0x4c, 0x10, 0x03, 0x12, 0x10, 0x0a, 0x0c, 0x53,
	0x54, 0x52, 0x49, 0x4e, 0x47, 0x5f, 0x41, 0x52, 0x52, 0x41, 0x59, 0x10, 0x04, 0x12, 0x11, 0x0a,
	0x0d, 0x49, 0x4e, 0x54, 0x45, 0x47, 0x45, 0x52, 0x5f, 0x41, 0x52, 0x52, 0x41, 0x59, 0x10, 0x05,
	0x12, 0x0f, 0x0a, 0x0b, 0x46, 0x4c, 0x4f, 0x41, 0x54, 0x5f, 0x41, 0x52, 0x52, 0x41, 0x59, 0x10,
	0x06, 0x12, 0x11, 0x0a, 0x0d, 0x42, 0x4f, 0x4f, 0x4c, 0x45, 0x41, 0x4e, 0x5f, 0x41, 0x52, 0x52,
	0x41, 0x59, 0x10, 0x07, 0x12, 0x08, 0x0a, 0x04, 0x45, 0x4e, 0x55, 0x4d, 0x10, 0x08, 0x12, 0x0e,
	0x0a, 0x0a, 0x45, 0x4e, 0x55, 0x4d, 0x5f, 0x41, 0x52, 0x52, 0x41, 0x59, 0x10, 0x09, 0x2a, 0xae,
	0x01, 0x0a, 0x08, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x06, 0x0a, 0x02, 0x45,
	0x51, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x4e, 0x45, 0x51, 0x10, 0x01, 0x12, 0x06, 0x0a, 0x02,
	0x47, 0x54, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x47, 0x54, 0x45, 0x10, 0x03, 0x12, 0x06, 0x0a,
	0x02, 0x4c, 0x54, 0x10, 0x04, 0x12, 0x07, 0x0a, 0x03, 0x4c, 0x54, 0x45, 0x10, 0x05, 0x12, 0x0c,
	0x0a, 0x08, 0x43, 0x4f, 0x4e, 0x54, 0x41, 0x49, 0x4e, 0x53, 0x10, 0x06, 0x12, 0x0a, 0x0a, 0x06,
	0x50, 0x52, 0x45, 0x46, 0x49, 0x58, 0x10, 0x07, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x55, 0x46, 0x46,
	0x49, 0x58, 0x10, 0x08, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x45, 0x47, 0x45, 0x58, 0x10, 0x09, 0x12,
	0x06, 0x0a, 0x02, 0x49, 0x4e, 0x10, 0x0a, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x4f, 0x54, 0x5f, 0x49,
	0x4e, 0x10, 0x0b, 0x12, 0x0b, 0x0a, 0x07, 0x42, 0x45, 0x54, 0x57, 0x45, 0x45, 0x4e, 0x10, 0x0c,
	0x12, 0x0f, 0x0a, 0x0b, 0x4e, 0x4f, 0x54, 0x5f, 0x42, 0x45, 0x54, 0x57, 0x45, 0x45, 0x4e, 0x10,
	0x0d, 0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x4f, 0x54, 0x5f, 0x4e, 0x55, 0x4c, 0x4c, 0x10, 0x0e, 0x42,
	0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_ng_driver_proto_rawDescOnce sync.Once
	file_ng_driver_proto_rawDescData = file_ng_driver_proto_rawDesc
)

func file_ng_driver_proto_rawDescGZIP() []byte {
	file_ng_driver_proto_rawDescOnce.Do(func() {
		file_ng_driver_proto_rawDescData = protoimpl.X.CompressGZIP(file_ng_driver_proto_rawDescData)
	})
	return file_ng_driver_proto_rawDescData
}

var file_ng_driver_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_ng_driver_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_ng_driver_proto_goTypes = []any{
	(ExtensionType)(0),     // 0: ng_proto.ExtensionType
	(Operator)(0),          // 1: ng_proto.Operator
	(*EnumValue)(nil),      // 2: ng_proto.EnumValue
	(*EnumArrayType)(nil),  // 3: ng_proto.EnumArrayType
	(*StringArray)(nil),    // 4: ng_proto.StringArray
	(*IntArray)(nil),       // 5: ng_proto.IntArray
	(*FloatArray)(nil),     // 6: ng_proto.FloatArray
	(*BooleanArray)(nil),   // 7: ng_proto.BooleanArray
	(*Condition)(nil),      // 8: ng_proto.Condition
	(*Extension)(nil),      // 9: ng_proto.Extension
	(*DriverMetadata)(nil), // 10: ng_proto.DriverMetadata
}
var file_ng_driver_proto_depIdxs = []int32{
	2,  // 0: ng_proto.EnumArrayType.values:type_name -> ng_proto.EnumValue
	1,  // 1: ng_proto.Condition.operator:type_name -> ng_proto.Operator
	4,  // 2: ng_proto.Condition.stringArray:type_name -> ng_proto.StringArray
	5,  // 3: ng_proto.Condition.intArray:type_name -> ng_proto.IntArray
	6,  // 4: ng_proto.Condition.floatArray:type_name -> ng_proto.FloatArray
	7,  // 5: ng_proto.Condition.boolArray:type_name -> ng_proto.BooleanArray
	0,  // 6: ng_proto.Extension.type:type_name -> ng_proto.ExtensionType
	2,  // 7: ng_proto.Extension.enumInfo:type_name -> ng_proto.EnumValue
	8,  // 8: ng_proto.Extension.conditions:type_name -> ng_proto.Condition
	9,  // 9: ng_proto.DriverMetadata.extensions:type_name -> ng_proto.Extension
	9,  // 10: ng_proto.DriverMetadata.dataPointExtensions:type_name -> ng_proto.Extension
	9,  // 11: ng_proto.DriverMetadata.actionExtensions:type_name -> ng_proto.Extension
	9,  // 12: ng_proto.DriverMetadata.eventExtensions:type_name -> ng_proto.Extension
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_ng_driver_proto_init() }
func file_ng_driver_proto_init() {
	if File_ng_driver_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ng_driver_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*EnumValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ng_driver_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*EnumArrayType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ng_driver_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*StringArray); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ng_driver_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*IntArray); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ng_driver_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*FloatArray); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ng_driver_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*BooleanArray); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ng_driver_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*Condition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ng_driver_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*Extension); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ng_driver_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*DriverMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_ng_driver_proto_msgTypes[0].OneofWrappers = []any{
		(*EnumValue_StringValue)(nil),
		(*EnumValue_IntValue)(nil),
		(*EnumValue_FloatValue)(nil),
		(*EnumValue_BoolValue)(nil),
	}
	file_ng_driver_proto_msgTypes[6].OneofWrappers = []any{
		(*Condition_StringValue)(nil),
		(*Condition_IntValue)(nil),
		(*Condition_FloatValue)(nil),
		(*Condition_BoolValue)(nil),
		(*Condition_StringArray)(nil),
		(*Condition_IntArray)(nil),
		(*Condition_FloatArray)(nil),
		(*Condition_BoolArray)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ng_driver_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ng_driver_proto_goTypes,
		DependencyIndexes: file_ng_driver_proto_depIdxs,
		EnumInfos:         file_ng_driver_proto_enumTypes,
		MessageInfos:      file_ng_driver_proto_msgTypes,
	}.Build()
	File_ng_driver_proto = out.File
	file_ng_driver_proto_rawDesc = nil
	file_ng_driver_proto_goTypes = nil
	file_ng_driver_proto_depIdxs = nil
}
