// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v5.29.0
// source: ng_device.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceProvisionConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Secret        string                 `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceProvisionConnectRequest) Reset() {
	*x = DeviceProvisionConnectRequest{}
	mi := &file_ng_device_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceProvisionConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceProvisionConnectRequest) ProtoMessage() {}

func (x *DeviceProvisionConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ng_device_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceProvisionConnectRequest.ProtoReflect.Descriptor instead.
func (*DeviceProvisionConnectRequest) Descriptor() ([]byte, []int) {
	return file_ng_device_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceProvisionConnectRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DeviceProvisionConnectRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

type DeviceProvisionConnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Common        *CommonResponse        `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	ProductId     int64                  `protobuf:"varint,2,opt,name=productId,proto3" json:"productId,omitempty"`
	TenantId      int64                  `protobuf:"varint,3,opt,name=tenantId,proto3" json:"tenantId,omitempty"`
	DeviceType    string                 `protobuf:"bytes,4,opt,name=deviceType,proto3" json:"deviceType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceProvisionConnectResponse) Reset() {
	*x = DeviceProvisionConnectResponse{}
	mi := &file_ng_device_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceProvisionConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceProvisionConnectResponse) ProtoMessage() {}

func (x *DeviceProvisionConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ng_device_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceProvisionConnectResponse.ProtoReflect.Descriptor instead.
func (*DeviceProvisionConnectResponse) Descriptor() ([]byte, []int) {
	return file_ng_device_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceProvisionConnectResponse) GetCommon() *CommonResponse {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *DeviceProvisionConnectResponse) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *DeviceProvisionConnectResponse) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *DeviceProvisionConnectResponse) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

type DeviceProvisionRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Gateway       bool                    `protobuf:"varint,1,opt,name=gateway,proto3" json:"gateway,omitempty"`
	DeviceName    string                  `protobuf:"bytes,2,opt,name=deviceName,proto3" json:"deviceName,omitempty"`
	Credentials   *DeviceCredentialsProto `protobuf:"bytes,3,opt,name=credentials,proto3" json:"credentials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceProvisionRequest) Reset() {
	*x = DeviceProvisionRequest{}
	mi := &file_ng_device_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceProvisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceProvisionRequest) ProtoMessage() {}

func (x *DeviceProvisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ng_device_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceProvisionRequest.ProtoReflect.Descriptor instead.
func (*DeviceProvisionRequest) Descriptor() ([]byte, []int) {
	return file_ng_device_proto_rawDescGZIP(), []int{2}
}

func (x *DeviceProvisionRequest) GetGateway() bool {
	if x != nil {
		return x.Gateway
	}
	return false
}

func (x *DeviceProvisionRequest) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *DeviceProvisionRequest) GetCredentials() *DeviceCredentialsProto {
	if x != nil {
		return x.Credentials
	}
	return nil
}

type DeviceCredentialsProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          int64                  `protobuf:"varint,1,opt,name=mode,proto3" json:"mode,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=clientId,proto3" json:"clientId,omitempty"`
	Csr           []byte                 `protobuf:"bytes,3,opt,name=csr,proto3" json:"csr,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceCredentialsProto) Reset() {
	*x = DeviceCredentialsProto{}
	mi := &file_ng_device_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceCredentialsProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceCredentialsProto) ProtoMessage() {}

func (x *DeviceCredentialsProto) ProtoReflect() protoreflect.Message {
	mi := &file_ng_device_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceCredentialsProto.ProtoReflect.Descriptor instead.
func (*DeviceCredentialsProto) Descriptor() ([]byte, []int) {
	return file_ng_device_proto_rawDescGZIP(), []int{3}
}

func (x *DeviceCredentialsProto) GetMode() int64 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *DeviceCredentialsProto) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *DeviceCredentialsProto) GetCsr() []byte {
	if x != nil {
		return x.Csr
	}
	return nil
}

func (x *DeviceCredentialsProto) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *DeviceCredentialsProto) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type DeviceProvisionResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Common        *CommonResponse            `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	DeviceInfo    *DeviceInfoProto           `protobuf:"bytes,2,opt,name=deviceInfo,proto3" json:"deviceInfo,omitempty"`
	Credentials   *DeviceCredentialsResponse `protobuf:"bytes,3,opt,name=credentials,proto3" json:"credentials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceProvisionResponse) Reset() {
	*x = DeviceProvisionResponse{}
	mi := &file_ng_device_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceProvisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceProvisionResponse) ProtoMessage() {}

func (x *DeviceProvisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ng_device_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceProvisionResponse.ProtoReflect.Descriptor instead.
func (*DeviceProvisionResponse) Descriptor() ([]byte, []int) {
	return file_ng_device_proto_rawDescGZIP(), []int{4}
}

func (x *DeviceProvisionResponse) GetCommon() *CommonResponse {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *DeviceProvisionResponse) GetDeviceInfo() *DeviceInfoProto {
	if x != nil {
		return x.DeviceInfo
	}
	return nil
}

func (x *DeviceProvisionResponse) GetCredentials() *DeviceCredentialsResponse {
	if x != nil {
		return x.Credentials
	}
	return nil
}

type DeviceCredentialsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          int64                  `protobuf:"varint,1,opt,name=mode,proto3" json:"mode,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=clientId,proto3" json:"clientId,omitempty"`
	Ca            string                 `protobuf:"bytes,3,opt,name=ca,proto3" json:"ca,omitempty"`
	Certificate   string                 `protobuf:"bytes,4,opt,name=certificate,proto3" json:"certificate,omitempty"`
	Username      string                 `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceCredentialsResponse) Reset() {
	*x = DeviceCredentialsResponse{}
	mi := &file_ng_device_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceCredentialsResponse) ProtoMessage() {}

func (x *DeviceCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ng_device_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceCredentialsResponse.ProtoReflect.Descriptor instead.
func (*DeviceCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_ng_device_proto_rawDescGZIP(), []int{5}
}

func (x *DeviceCredentialsResponse) GetMode() int64 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *DeviceCredentialsResponse) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *DeviceCredentialsResponse) GetCa() string {
	if x != nil {
		return x.Ca
	}
	return ""
}

func (x *DeviceCredentialsResponse) GetCertificate() string {
	if x != nil {
		return x.Certificate
	}
	return ""
}

func (x *DeviceCredentialsResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *DeviceCredentialsResponse) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

var File_ng_device_proto protoreflect.FileDescriptor

var file_ng_device_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6e, 0x67, 0x5f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x08, 0x6e, 0x67, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0f, 0x6e, 0x67, 0x5f,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x49, 0x0a, 0x1d,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x43,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x22, 0xac, 0x01, 0x0a, 0x1e, 0x44, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x06, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6e, 0x67, 0x5f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x52, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x65,
	0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x74, 0x65,
	0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x96, 0x01, 0x0a, 0x16, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x64,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x42, 0x0a, 0x0b, 0x63,
	0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x20, 0x2e, 0x6e, 0x67, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x52, 0x0b, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x22,
	0x92, 0x01, 0x0a, 0x16, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x61, 0x6c, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x73,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x63, 0x73, 0x72, 0x12, 0x1a, 0x0a, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x22, 0xcd, 0x01, 0x0a, 0x17, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x50,
	0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x30, 0x0a, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x18, 0x2e, 0x6e, 0x67, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x06, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x12, 0x39, 0x0a, 0x0a, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6e, 0x67, 0x5f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x52, 0x0a, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x45, 0x0a,
	0x0b, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6e, 0x67, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0b, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x61, 0x6c, 0x73, 0x22, 0xb5, 0x01, 0x0a, 0x19, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x43,
	0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x63, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x63, 0x61, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x42, 0x09, 0x5a, 0x07,
	0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ng_device_proto_rawDescOnce sync.Once
	file_ng_device_proto_rawDescData = file_ng_device_proto_rawDesc
)

func file_ng_device_proto_rawDescGZIP() []byte {
	file_ng_device_proto_rawDescOnce.Do(func() {
		file_ng_device_proto_rawDescData = protoimpl.X.CompressGZIP(file_ng_device_proto_rawDescData)
	})
	return file_ng_device_proto_rawDescData
}

var file_ng_device_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_ng_device_proto_goTypes = []any{
	(*DeviceProvisionConnectRequest)(nil),  // 0: ng_proto.DeviceProvisionConnectRequest
	(*DeviceProvisionConnectResponse)(nil), // 1: ng_proto.DeviceProvisionConnectResponse
	(*DeviceProvisionRequest)(nil),         // 2: ng_proto.DeviceProvisionRequest
	(*DeviceCredentialsProto)(nil),         // 3: ng_proto.DeviceCredentialsProto
	(*DeviceProvisionResponse)(nil),        // 4: ng_proto.DeviceProvisionResponse
	(*DeviceCredentialsResponse)(nil),      // 5: ng_proto.DeviceCredentialsResponse
	(*CommonResponse)(nil),                 // 6: ng_proto.CommonResponse
	(*DeviceInfoProto)(nil),                // 7: ng_proto.DeviceInfoProto
}
var file_ng_device_proto_depIdxs = []int32{
	6, // 0: ng_proto.DeviceProvisionConnectResponse.common:type_name -> ng_proto.CommonResponse
	3, // 1: ng_proto.DeviceProvisionRequest.credentials:type_name -> ng_proto.DeviceCredentialsProto
	6, // 2: ng_proto.DeviceProvisionResponse.common:type_name -> ng_proto.CommonResponse
	7, // 3: ng_proto.DeviceProvisionResponse.deviceInfo:type_name -> ng_proto.DeviceInfoProto
	5, // 4: ng_proto.DeviceProvisionResponse.credentials:type_name -> ng_proto.DeviceCredentialsResponse
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_ng_device_proto_init() }
func file_ng_device_proto_init() {
	if File_ng_device_proto != nil {
		return
	}
	file_ng_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ng_device_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ng_device_proto_goTypes,
		DependencyIndexes: file_ng_device_proto_depIdxs,
		MessageInfos:      file_ng_device_proto_msgTypes,
	}.Build()
	File_ng_device_proto = out.File
	file_ng_device_proto_rawDesc = nil
	file_ng_device_proto_goTypes = nil
	file_ng_device_proto_depIdxs = nil
}
