// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v5.29.0
// source: ng_notify.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceSessionEventNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          SessionType            `protobuf:"varint,1,opt,name=type,proto3,enum=ng_proto.SessionType" json:"type,omitempty"`
	Event         SessionEvent           `protobuf:"varint,2,opt,name=event,proto3,enum=ng_proto.SessionEvent" json:"event,omitempty"`
	SessionInfo   *SessionInfoProto      `protobuf:"bytes,3,opt,name=sessionInfo,proto3" json:"sessionInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceSessionEventNotify) Reset() {
	*x = DeviceSessionEventNotify{}
	mi := &file_ng_notify_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceSessionEventNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceSessionEventNotify) ProtoMessage() {}

func (x *DeviceSessionEventNotify) ProtoReflect() protoreflect.Message {
	mi := &file_ng_notify_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceSessionEventNotify.ProtoReflect.Descriptor instead.
func (*DeviceSessionEventNotify) Descriptor() ([]byte, []int) {
	return file_ng_notify_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceSessionEventNotify) GetType() SessionType {
	if x != nil {
		return x.Type
	}
	return SessionType_SESSION_UNSET
}

func (x *DeviceSessionEventNotify) GetEvent() SessionEvent {
	if x != nil {
		return x.Event
	}
	return SessionEvent_SESSION_EVENT_UNSET
}

func (x *DeviceSessionEventNotify) GetSessionInfo() *SessionInfoProto {
	if x != nil {
		return x.SessionInfo
	}
	return nil
}

type HousekeeperTaskNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityType    string                 `protobuf:"bytes,1,opt,name=entityType,proto3" json:"entityType,omitempty"`
	EntityId      int64                  `protobuf:"varint,2,opt,name=entityId,proto3" json:"entityId,omitempty"`
	TenantId      int64                  `protobuf:"varint,3,opt,name=tenantId,proto3" json:"tenantId,omitempty"`
	Type          HousekeeperTaskType    `protobuf:"varint,4,opt,name=type,proto3,enum=ng_proto.HousekeeperTaskType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HousekeeperTaskNotify) Reset() {
	*x = HousekeeperTaskNotify{}
	mi := &file_ng_notify_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HousekeeperTaskNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HousekeeperTaskNotify) ProtoMessage() {}

func (x *HousekeeperTaskNotify) ProtoReflect() protoreflect.Message {
	mi := &file_ng_notify_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HousekeeperTaskNotify.ProtoReflect.Descriptor instead.
func (*HousekeeperTaskNotify) Descriptor() ([]byte, []int) {
	return file_ng_notify_proto_rawDescGZIP(), []int{1}
}

func (x *HousekeeperTaskNotify) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *HousekeeperTaskNotify) GetEntityId() int64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *HousekeeperTaskNotify) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *HousekeeperTaskNotify) GetType() HousekeeperTaskType {
	if x != nil {
		return x.Type
	}
	return HousekeeperTaskType_HOUSEKEEPER_TASK_UNSET
}

var File_ng_notify_proto protoreflect.FileDescriptor

var file_ng_notify_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6e, 0x67, 0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x08, 0x6e, 0x67, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0f, 0x6e, 0x67, 0x5f,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb1, 0x01, 0x0a,
	0x18, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x29, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x6e, 0x67, 0x5f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x2c, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x6e, 0x67, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x05, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x12, 0x3c, 0x0a, 0x0b, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66,
	0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6e, 0x67, 0x5f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x52, 0x0b, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f,
	0x22, 0xa2, 0x01, 0x0a, 0x15, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72,
	0x54, 0x61, 0x73, 0x6b, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74,
	0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74,
	0x49, 0x64, 0x12, 0x31, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x1d, 0x2e, 0x6e, 0x67, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x48, 0x6f, 0x75, 0x73,
	0x65, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ng_notify_proto_rawDescOnce sync.Once
	file_ng_notify_proto_rawDescData = file_ng_notify_proto_rawDesc
)

func file_ng_notify_proto_rawDescGZIP() []byte {
	file_ng_notify_proto_rawDescOnce.Do(func() {
		file_ng_notify_proto_rawDescData = protoimpl.X.CompressGZIP(file_ng_notify_proto_rawDescData)
	})
	return file_ng_notify_proto_rawDescData
}

var file_ng_notify_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ng_notify_proto_goTypes = []any{
	(*DeviceSessionEventNotify)(nil), // 0: ng_proto.DeviceSessionEventNotify
	(*HousekeeperTaskNotify)(nil),    // 1: ng_proto.HousekeeperTaskNotify
	(SessionType)(0),                 // 2: ng_proto.SessionType
	(SessionEvent)(0),                // 3: ng_proto.SessionEvent
	(*SessionInfoProto)(nil),         // 4: ng_proto.SessionInfoProto
	(HousekeeperTaskType)(0),         // 5: ng_proto.HousekeeperTaskType
}
var file_ng_notify_proto_depIdxs = []int32{
	2, // 0: ng_proto.DeviceSessionEventNotify.type:type_name -> ng_proto.SessionType
	3, // 1: ng_proto.DeviceSessionEventNotify.event:type_name -> ng_proto.SessionEvent
	4, // 2: ng_proto.DeviceSessionEventNotify.sessionInfo:type_name -> ng_proto.SessionInfoProto
	5, // 3: ng_proto.HousekeeperTaskNotify.type:type_name -> ng_proto.HousekeeperTaskType
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_ng_notify_proto_init() }
func file_ng_notify_proto_init() {
	if File_ng_notify_proto != nil {
		return
	}
	file_ng_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ng_notify_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ng_notify_proto_goTypes,
		DependencyIndexes: file_ng_notify_proto_depIdxs,
		MessageInfos:      file_ng_notify_proto_msgTypes,
	}.Build()
	File_ng_notify_proto = out.File
	file_ng_notify_proto_rawDesc = nil
	file_ng_notify_proto_goTypes = nil
	file_ng_notify_proto_depIdxs = nil
}
